Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: org.example.handler.LambdaHandler::handleRequest
      CodeUri: /home/herbs/aws/labs-java/aws-cognito-auth
      Runtime: java11
      Architectures:
        - x86_64